spring:
  cloud:
    gateway:
      routes:
        #        - id: baidu_route
        #          uri: http://www.baidu.com
        #          predicates:
        #            - Query=url,baidu
        #
        #        - id: qq_route
        #          uri: http://www.qq.com
        #          predicates:
        #            - Query=url,qq

        # 在网关增加三级分类的路由

        #商品服务路由
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        #优惠服务路由
        - id: coupon_route
          uri: lb://gulimall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        #第三方服务路由
        - id: third_party_route
          # 路由给third-party，lb代表负载均衡
          uri: lb://gulimall-third-party
          # 什么情况下路由给它
          predicates:
            # 默认前端项目都带上api前缀
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        #会员服务路由
        - id: member_route
          # 路由给third-party，lb代表负载均衡
          uri: lb://gulimall-member
          # 什么情况下路由给它
          predicates:
            # 默认前端项目都带上api前缀
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        #库存服务路由
        - id: ware_route
          # 路由给third-party，lb代表负载均衡
          uri: lb://gulimall-ware
          # 什么情况下路由给它
          predicates:
            # 默认前端项目都带上api前缀
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        #人人后台系统路由
        - id: admin_route
          # 路由给renren-fast，lb代表负载均衡
          uri: lb://renren-fast
          # 什么情况下路由给它
          predicates:
            # 默认前端项目都带上api前缀
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        #域名转发路由-商品首页
        - id: gulimall_host_route
          uri: lb://gulimall-product
          predicates:
            - Host=gulimall.com,item.gulimall.com

        #域名转发路由-商品检索页
        - id: gulimall_search_route
          uri: lb://gulimall-search
          predicates:
            - Host=search.gulimall.com

        #域名转发路由-认证服务
        - id: gulimall_auth_route
          uri: lb://gulimall-auth-server
          predicates:
            - Host=auth.gulimall.com

        #域名转发路由-购物车服务
        - id: gulimall_cart_route
          uri: lb://gulimall-cart
          predicates:
            - Host=cart.gulimall.com

        #域名转发路由-订单服务
        - id: gulimall_order_route
          uri: lb://gulimall-order
          predicates:
            - Host=order.gulimall.com

        #域名转发路由-会员服务
        - id: gulimall_member_route
          uri: lb://gulimall-member
          predicates:
            - Host=member.gulimall.com

        #域名转发路由-秒杀服务
        - id: gulimall_seckill_route
          uri: lb://gulimall-seckill
          predicates:
            - Host=seckill.gulimall.com
