server:
  port: 8080

spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: nacos-service.gulimall:8848
    alicloud:
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        appcode: 3bc996b9d54f448ea100135c4cbec152
        template_id: TPL_0000
