server:
  port: 8080

spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: nacos-service.gulimall:8848

  redis:
    port: 6379
    host: redis.gulimall

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true
  session:
    store-type: redis

#配置线程池
gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10



